language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "pypy"
services:
 - "cassandra"
install:
 - "easy_install -U distribute"
 - "pip install ."
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: "python setup.py test"
