language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "pypy"
before-install:
 - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
 - sudo service cassandra start
 - sleep 3
install: "pip install . --use-mirrors"
script: "python setup.py test"
